language: ruby
services:
- postgresql
rvm:
- 2.5.0

node_js:
- "node"

install:
- gem uninstall bundler
- gem install bundler --version '1.7.4'
- bundle install
- rails db:migrate RAILS_ENV=test
- nvm install 14.2

before_script:
- npm install

script: 
- rake
# - bundle exec rubocop
- bundle exec rspec
# - npm test
# - npm run lint
# 
